import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Container from "./components/container";
import Nav from "./components/nav";
import Footer from "./components/footer";

const inter = Inter({
  weight: ["400", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="text-[clamp(2vw,2vi+400,(1.1vw))] overflow-x-hidden no-scrollbar"
    >
      <body
        className={`${inter.className} antialiased`}
      >
        <Container>
          <Nav />
          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
